### ISSUE TITLE
Add usage documentation?

### ISSUE THREAD

**Issue by ChristianSauer** [dotnet/nbgv#26]
Ok, I'm new to dot net core versioning and github actions - I only tagged packages manually before.
I found nbgv and would like to use it and it's github action. But I am utterly confused at which step I  would need to add this action and what I would need to do after adding this action.

Would be totally great if the readme contains some usage instructions for dummies.
I would even be prepared to add a PR, but honestly atm I am lacking a good starting point to bootstrap myself out of confusion.

**Comment by AArnott** [comment]
You would put this action near the top of your existing pipeline/workflow. This will allow you to consume its outputs in the rest of your build.

If you're developing .NET projects however, the github action isn't particularly relevant because by far the easiest way to version your projects is to install the nerdbank.gitversioning nuget package.

**Comment by Ian1971** [comment]
> If you're developing .NET projects however, the github action isn't particularly relevant because by far the easiest way to version your projects is to install the nerdbank.gitversioning nuget package.

Is there a way to get the current version to be used in another github action (docker build) without using the nbgv github action?

**Comment by Ian1971** [comment]
Sorry if not clear. It was in response to this "If you're developing .NET projects however, the github action isn't particularly relevant because by far the easiest way to version your projects is to install the nerdbank.gitversioning nuget package."  which seems to be saying you don't need the github action if you are using the nuget package.

**Comment by AArnott** [comment]
Yes, that's true. I hear that people's docker builds tend to not map in the .git directory, so nb.gv (the nuget package) doesn't work inside it. We should take such discussions over to that repo. In fact this one is already discussed: https://github.com/dotnet/Nerdbank.GitVersioning/issues/416
