### ISSUE TITLE
Publish 0.4.0 on GitHub Marketplace

### ISSUE THREAD

**Issue by mausch** [dotnet/nbgv#38]
Hi and thanks for this tool!

https://github.com/marketplace/actions/nerdbank-gitversioning shows 0.3.1 as the latest version.
However If I try to use that I get that add-path error that apparently was fixed in 0.4.0.
It seems that 0.4.0 needs to be published somehow on the GitHub Marketplace?

**Comment by AArnott** [comment]
I would love to. But since being adopted by the .NET Foundation I have been unable to. The Foundation has to accept the GitHub Marketplace terms and conditions first, and I have been unable to get the Foundation admins to respond to my emails. 

![image](https://user-images.githubusercontent.com/3548/106367254-6cb5c880-62fe-11eb-9796-434591aa571a.png)

I may transfer the repo off the `dotnet` account if they continue to be unresponsive.

**Comment by AArnott** [comment]
Hey, they responded this time! It's published.
